nanoutils/nanoutils

SIZES.md
lib/unfold/index.js
lib/unfold/index.js.flow
lib/unfold/unfold.test.js

[Ramda's unfold](http://ramdajs.com/docs/#unfold)

New method: unfold (110 B)

---

SIZES.md
lib/transpose/index.js
lib/transpose/index.js.flow
lib/transpose/transpose.test.js

[Ramda's transpose](http://ramdajs.com/docs/#transpose)

New method: transpose (104 B)

---

SIZES.md
lib/tryCatch/index.js
lib/tryCatch/index.js.flow
lib/tryCatch/tryCatch.test.js

[Ramda's tryCatch](http://ramdajs.com/docs/#tryCatch)

New method: tryCatch (114 B)

---

SIZES.md
lib/toPairs/index.js
lib/toPairs/index.js.flow
lib/toPairs/toPairs.test.js
lib/toPairsIn/index.js
lib/toPairsIn/index.js.flow
lib/toPairsIn/toPairsIn.test.js

[Ramda's toPairs](http://ramdajs.com/docs/#toPairs)
[Ramda's toPairsIn](http://ramdajs.com/docs/#toPairsIn)
They're similar, so in one PR.

New methods: toPairs (62 B), toPairsIn (92 B)

---

SIZES.md
lib/toLower/index.js
lib/toLower/index.js.flow
lib/toLower/toLower.test.js
lib/toUpper/index.js
lib/toUpper/index.js.flow
lib/toUpper/toUpper.test.js

[Ramda's toLower](http://ramdajs.com/docs/#toLower)
[Ramda's toUpper](http://ramdajs.com/docs/#toUpper)

New methods: toLower (40 B), toUpper (41 B)

---

SIZES.md
lib/call/call.test.js
lib/call/index.js
lib/call/index.js.flow

[Ramda's call](http://ramdajs.com/docs/#call)
Made currying for function argument and other arguments, do not  think it's necessary to make currying for every argument

New method: call (69 B)

---

SIZES.md
lib/bind/bind.test.js
lib/bind/index.js
lib/bind/index.js.flow

[Ramda's bind](http://ramdajs.com/docs/#bind)
Ramda does not provide args passing to binded function, so I haven't made it too. Should I?

New method: bind (85 B)

---

SIZES.md
lib/juxt/index.js
lib/juxt/juxt.test.js
lib/median/index.js
lib/median/median.test.js

[`R.juxt`](http://ramdajs.com/docs/#juxt) method + tests

New method: juxt (Size: 56 B)

---

SIZES.md
lib/chain/chain.test.js
lib/chain/index.js
lib/chain/index.js.flow

[Ramda's chain](http://ramdajs.com/docs/#chain)

New method: chain (117 B)

---

lib/reduceBy/index.js
lib/reduceBy/reduceBy.test.js
lib/reduceRight/index.js
lib/reduceRight/reduceRight.test.js
lib/reduceWhile/index.js
lib/reduceWhile/reduceWhile.test.js
lib/reduceWhileRight/index.js
lib/reduceWhileRight/reduceWhileRight.test.js

[`R.reduce`](http://ramdajs.com/docs/#reduce)
[`R.reduceRight`](http://ramdajs.com/docs/#reduceRight)
[`R.reduceBy`](http://ramdajs.com/docs/#reduceBy)
[`R.reduceWhile`](http://ramdajs.com/docs/#reduceWhile)
`R.reduceWhileRight` (no Ramda equivalent)

reduce methods

---

lib/range/index.js
lib/range/range.test.js

[`R.range`](http://ramdajs.com/docs/#range)

New method: range (Size: 108 B)

---

lib/tap/index.js
lib/tap/tap.test.js

[`R.tap`](http://ramdajs.com/docs/#tap)

New method: tap (Size: 107 B)

---

lib/scan/index.js
lib/scan/scan.test.js

[`R.scan`](http://ramdajs.com/docs/#scan)

:tada: New method: scan (Size: 127 B)

---

lib/insert/index.js
lib/insert/insert.test.js
lib/insertAll/index.js
lib/insertAll/insertAll.test.js

[`R.insert`](http://ramdajs.com/docs/#insert)
[`R.insertAll`](http://ramdajs.com/docs/#insertAll)

insert + insertAll methods

---

SIZES.md
lib/forEach/forEach.test.js
lib/forEach/index.js
lib/forEach/index.js.flow

[Ramda's forEach](http://ramdajs.com/docs/#forEach)

New method: forEach (102 B)

---

SIZES.md
lib/endsWith/endsWith.test.js
lib/endsWith/index.js
lib/endsWith/index.js.flow

[Ramda's endsWith](http://ramdajs.com/docs/#endsWith)

New method: endsWith (90 B)

---

SIZES.md
lib/endsWith/index.js
lib/has/has.test.js
lib/has/index.js
lib/has/index.js.flow
lib/hasIn/hasIn.test.js
lib/hasIn/index.js
lib/hasIn/index.js.flow

[Ramda has](http://ramdajs.com/docs/#has)
[Ramda hasIn](http://ramdajs.com/docs/#hasIn)
P.S. sorry, but in this branch contains commit for fixing `endsWith` method

New methods: has (85 B), hasIn (85 B)

---

SIZES.md
lib/once/index.js
lib/once/once.test.js

[Ramda once](http://ramdajs.com/docs/#once)
Ramda does not curry returned function, so did I, but we could think about it.

New method: once (60 B)

---

SIZES.md
lib/pair/index.js
lib/pair/pair.test.js

[Ramda pair](http://ramdajs.com/docs/#pair)

New method: pair (83 B)

---

misc/cli/time.js

use `yarn time <...methods>` to update certain methods, other methods remain same, `<...methods>.json` will be updated only for methods which are passed as arguments
use `yarn time` to update all times

Make yarn time incremental

---

SIZES.md
lib/where/index.js
lib/where/where.test.js
lib/whereEq/index.js
lib/whereEq/whereEq.test.js

[Ramda where](http://ramdajs.com/docs/#where)

🎉 New methods: where (116 B), whereEq (376 B)

---

SIZES.md
lib/_internal/_words/index.js
lib/camelCase/camelCase.test.js
lib/camelCase/index.js
lib/snakeCase/index.js
lib/snakeCase/snakeCase.test.js

based on lodash [camelCase](https://lodash.com/docs/4.17.5#camelCase) and [snakeCase](https://lodash.com/docs/4.17.5#snakeCase)

🎉 New methods: camelCase (143 B) and snakeCase (127 B)

---

SIZES.md
lib/dropRepeats/dropRepeats.test.js
lib/dropRepeats/index.js
lib/dropRepeatsWith/dropRepeatsWith.test.js
lib/dropRepeatsWith/index.js

[Ramda dropRepeats](http://ramdajs.com/docs/#dropRepeats)
[Ramda dropRepeatsWith](http://ramdajs.com/docs/#dropRepeatsWith)

New methods: dropRepeats (375 B), dropRepeatsWIth (119 B)

---

SIZES.md
lib/mergeAll/index.js
lib/mergeAll/mergeAll.test.js

[Ramda mergeAll](http://ramdajs.com/docs/#mergeAll)

New method: mergeAll (62 B)

---

SIZES.md
lib/propEq/index.js
lib/propEq/propEq.test.js
lib/propIs/index.js
lib/propIs/propIs.test.js
lib/propOr/index.js
lib/propOr/propOr.test.js

[Ramda propEq](http://ramdajs.com/docs/#propEq)
[Ramda propIs](http://ramdajs.com/docs/#propIs)
[Ramda propOr](http://ramdajs.com/docs/#propOr)

🎉 New methods: propEq (383 B), propIs (135 B), propOr (110 B)

---

SIZES.md
lib/lensProp/index.js
lib/lensProp/lensProp.test.js

[Ramda lensProp](http://ramdajs.com/docs/#lensProp)

New method: lensProp (105 B)

---

SIZES.md
lib/match/index.js
lib/match/match.test.js

[Ramda match](http://ramdajs.com/docs/#match)

New method: match (90 B)

---

SIZES.md
lib/propSatisfies/index.js
lib/propSatisfies/propSatisfies.test.js

[Ramda propSatisfies](http://ramdajs.com/docs/#propSatisfies)

New method: propSatisfies (106 B)

---

docs/docs/methods.md
lib/composeT/composeT.test.js
lib/concat/concat.test.js
lib/cond/cond.test.js
lib/construct/construct.test.js
lib/constructN/constructN.test.js
lib/contains/contains.test.js
lib/converge/converge.test.js
lib/countBy/countBy.test.js
lib/curry/curry.test.js
lib/curryN/curryN.test.js

* refactor tests
* add tests for docs and in general if they are absent
* add C-methods to docs

test & refactor: add all C-methods

---

docs/docs/methods.md
lib/groupBy/groupBy.test.js

docs: add G-methods

---

docs/docs/methods.md

docs: add H-methods

---

lib/_internal/_words/_words.test.js

Added missing tests for `_words`

test: add missing tests for '_words' helper

---

docs/.vuepress/config.js

Added repo link in header and 'Edit this page' link to engage and help people who want to contribute.

add repo link, add 'Edit this page' link

---

SIZES.md
package.json
yarn.lock

enhance: add np

---

SIZES.md
lib/_internal/_shallow_clone/index.js
lib/_internal/_shallow_clone/shallow_clone.test.js
lib/assoc/assoc.js
lib/assocPath/assocPath.js
lib/clone/clone.test.js
lib/clone/index.js
lib/reduceBy/index.js
lib/reduceBy/reduceBy.test.js

Solution for https://github.com/nanoutils/nanoutils/issues/176

enhance: reduceBy immutability fix

---

package.json
yarn.lock

Remove git-dependency:
1. Changes were released (https://github.com/gajus/create-index/releases/tag/v2.5.0)
2. Slow

🔄 update create-index 🚀

---

SIZES.md
SIZES_CJS.md
lib/lensPath/index.js
lib/lensPath/lensPath.test.js

fix: lensPath + set should not mutate original source
